/* Localized strings contents for default localized contents */ 

TIZEN_L10N=
{
	"do_not_use" : "do_not_use",
	"map_loading" : "Map Loading",
	"exit_reminder" : "Are you sure you want to exit? Widget and off-track notification will be turned off.",
	"hello" : "Hello",
	"screen" : "Screen",
	"always_on" : "Always On",
	"normal" : "Normal",
	"show_current_position" : "Show Current Position",
	"on" : "On",
	"off" : "Off",
	"map_orientation" : "Map Orientation",
	"direction_of_travel" : "Direction of Travel",
	"north" : "North",
	"trace_current_route" : "Show GPS Track",
	"set_center" : "Set Center to Current Location",
	"follow_route" : "Follow Route",
	"off_track_notification" : "Off-Route Notification",
	"map_engine" : "Map Engine",
	"map_type" : "Map Type",
	"hiking" : "Hiking",
	"cycling" : "Biking",
	"add_route" : "Add Route",
	"new_route" : "New Route",
	"gpx_route_tracker" : "GPX Route Tracker",
	"initializing_download" : "Initializing Download",
	"analyzing_route" : "Analyzing Route",
	"download_completed" : "Download Completed",
	"remove_route" : "Remove Route",
	"download_failed" : "Download Failed",
	"no_route" : "No Route",
	"routes" : "Routes",
	"downloading" : "Downloading",
	"not_set" : "Not Set",
	"route" : "Route",
	"deviation" : "Deviation",
	"distance_remaining" : "Distance Remaining",
	"route_name" : "Route Name",
	"save_file" : "Save",
	"gpx_file_url" : "GPX File URL",
	"success" : "Success",
	"try_again" : "Try Again",
	"wait_gps" : "Waiting for GPS Signal",
	"wrong_format" : "GPX File format incorrect. Choose another file. ",
	"error" : "Error",
	"remove" : "Remove",
	"new" : "New",
	"off_route_content" : "You are off-route.",
	"distance_to_nearest_point" : "Distance to the nearest point on the route"
};
